### PR TITLE
Update 2.x to Kotlin 1.4.0

### PR DESCRIPTION
**Pull request by thecodewarrior**
What it says on the tin :)

I had to make a couple of changes to do this, however. 
- I had to update Gradle to 5.6.4 to support the Kotlin 1.4.0 plugin
- Something about Kotlin's reflection broke, so I had to make `FMLKotlinModTarget` use plain Java reflection.

I also made a few changes to the readme file. 
- I added the library versions as badges to the top.
- I added an explanation that you have to update Gradle to use the new Kotlin plugin, and that using the new Kotlin plugin is optional.
- I added a mention of the slim jar to the Gradle example.

### CODE REVIEW

**Comment by autaut03** [comment]
Hey! Thank you! I'm gonna do some cleanup regarding #29 and then publish a new version.

**Comment by thecodewarrior** [comment]
Any updates on this?

**Comment by thecodewarrior** [comment]
I've got a pending update to my library that's being blocked by this. The library hasn't been released publically on CF, but it uses kottle from the curseforge maven, so I can't easily release a Kotlin 1.4 update until this is released.

**Comment by thecodewarrior** [comment]
Any updates on this?

**Comment by thecodewarrior** [comment]
I hate to be a nag, but does anything else need to be done before this is released?

**Pull request merged**
